### ISSUE TITLE
some errors happened when run the command 'pytest -v'

### ISSUE THREAD

**Issue by Dovehya** [brsynth/RetroPathRL#9] opened 2021-04-26 12:29 UTC
Hi, @tduigou 
when I tried to run the command 'pytest -v', I got some failed information:
`=============================================== short test summary info ===============================================
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_proper_root_initialisation - AttributeError: module 'signal' has n...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_terminal_state_false - AttributeError: module 'signal' has no attr...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_terminal_state_true_unavailable - AttributeError: module 'signal' ...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_proper_child_addition_821_rule_94682_moves - AssertionError: asser...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_proper_child_addition_821_rule_94682_moves_state - UnboundLocalErr...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_proper_child_addition_821_rule_117465_moves - UnboundLocalError: l...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_expand_821 - UnboundLocalError: local variable 'i_94682' reference...
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_expand_90191 - IndexError: list index out of range
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_node_expanded - assert [] != []
FAILED tests/test_MCTS_node.py::TestMCTSNode::test_node_rollout_possible - assert |NBBJYMSMWIIQGU-UHFFFAOYSA-N| != |N...
FAILED tests/test_cli.py::test_run_with_timeout - AttributeError: module 'signal' has no attribute 'SIGKILL'
FAILED tests/test_compound.py::TestCompound::test_apply_transformation_sets - assert (False)
FAILED tests/test_compound.py::TestCompound::test_apply_transformation_sets_parallel - assert (False)
FAILED tests/test_compound.py::TestCompound::test_apply_transformation_sets_different_products - IndexError: list ind...
FAILED tests/test_compound.py::TestCompound::test_apply_transformation_sets_different_products_parallel - IndexError:...
FAILED tests/test_compound.py::TestCompound::test_similarity_substrate_and_product_equal_1 - IndexError: list index o...
FAILED tests/test_compound.py::TestCompound::test_similarity_substrate_and_product_different_1 - IndexError: list ind...
FAILED tests/test_compound.py::TestCompound::test_stoechiometry_3 - AttributeError: module 'signal' has no attribute ...
FAILED tests/test_compound.py::TestCompound::test_rule_with_timeout - AttributeError: module 'signal' has no attribut...
FAILED tests/test_state.py::TestState::test_GetMoves - AssertionError: assert set() == {'MNXR103108_...13_MNXM90191'}
FAILED tests/test_state.py::TestState::test_ApplyMoves - UnboundLocalError: local variable 'i' referenced before assi...
====================================== 21 failed, 98 passed in 134.91s (0:02:14) ======================================`

before this, I haved modified the code as you committed to the issues. And I have also installed the MongoDB cache from brsynth/rp3_cache depot. 

Did I omit something when operated according to README.md? 
Thanks so much!

**Comment by tduigou** [comment] 2021-04-26 13:30
Hi @Dovehya,
Could try again but double check the conda environment (`MCTS` in the README > installalation section) has been activated before?

From the root folder:
```
conda activate MCTS
python change_config.py --use_cache True --add_Hs True
pytest -v
```

All the best,

**Comment by Dovehya** [comment] 2021-04-27 03:13
Thanks for your reply.
And it suddenly occurred to me that I run the RetroPathRL on the Windows System.Would it be this reason?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "brsynth/RetroPathRL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [brsynth/RetroPathRL] some errors happened when run the command 'pytest -v' (#9)





 
Hi @Dovehya,
 
Could you try again but double check the conda environment (MCTS in the README &gt; installalation section) has been activated before?
 
From the root folder:
 conda activate MCTS python change_config.py --use_cache True --add_Hs True pytest -v  
All the best,

**Comment by Dovehya** [comment] 2021-04-27 06:12
Hi， @tduigou 
I tried to run it on the Ubuntu System, and some errors disappeared.But some mistakes seems happened with the DB Cache. The error information are as follows:
`=================================== FAILURES ===================================
_________________________________ test_connect _________________________________

    def test_connect():  # Will not work in the DB is not up!!
        mgr = Manager()
>       mgr.connect()

rp3_dcache/test/test_Manager.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rp3_dcache/rp3_dcache/Manager.py:46: in connect
    self.client = MongoClient(host=self.host, port=self.port, username=self.username, password=self.password)
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in __init__
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in <genexpr>
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:539: in validate
    value = validator(option, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

key = 'username', dummy = 'captain'

    def raise_config_error(key, dummy):
        """Raise ConfigurationError with the given key name."""
>       raise ConfigurationError("Unknown option %s" % (key,))
E       pymongo.errors.ConfigurationError: Unknown option username

../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:117: ConfigurationError
_________________________________ test_insert __________________________________

    def test_insert():
        mgr = Manager()
>       mgr.connect()

rp3_dcache/test/test_Manager.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rp3_dcache/rp3_dcache/Manager.py:46: in connect
    self.client = MongoClient(host=self.host, port=self.port, username=self.username, password=self.password)
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in __init__
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in <genexpr>
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:539: in validate
    value = validator(option, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

key = 'username', dummy = 'captain'

    def raise_config_error(key, dummy):
        """Raise ConfigurationError with the given key name."""
>       raise ConfigurationError("Unknown option %s" % (key,))
E       pymongo.errors.ConfigurationError: Unknown option username

../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:117: ConfigurationError
__________________________________ test_find ___________________________________

    def test_find():
        mgr = Manager()
>       mgr.connect()

rp3_dcache/test/test_Manager.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rp3_dcache/rp3_dcache/Manager.py:46: in connect
    self.client = MongoClient(host=self.host, port=self.port, username=self.username, password=self.password)
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in __init__
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/mongo_client.py:422: in <genexpr>
    for k, v in keyword_opts.items())
../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:539: in validate
    value = validator(option, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

key = 'username', dummy = 'captain'

    def raise_config_error(key, dummy):
        """Raise ConfigurationError with the given key name."""
>       raise ConfigurationError("Unknown option %s" % (key,))
E       pymongo.errors.ConfigurationError: Unknown option username

../../../anaconda3/envs/MCTS/lib/python3.6/site-packages/pymongo/common.py:117: ConfigurationError
==================== 3 failed, 116 passed in 35.34 seconds =====================`

There were some configuration errors, but I have already run the command `docker-compose -f service/run/mongo.yml up -d`,and this is the result.
`CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS                                           NAMES
918867ca8401   mongo-express   "tini -- /docker-ent…"   30 minutes ago   Up 30 minutes   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp       run_mongo-express_1
0f40ed9cead0   mongo           "docker-entrypoint.s…"   30 minutes ago   Up 30 minutes   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   run_mongo_1
`

Thanks. Looking forward to your reply.

**Comment by tduigou** [comment] 2021-04-27 06:21
> Thanks for your reply. And it suddenly occurred to me that I run the RetroPathRL on the Windows System.Would it be this reason?

Hi @Dovehya, you are right, the signal package is the reason. RetroPath RL make use of the signal package to handle job timeout, but the signal package isn't available on Windows.

**Comment by tduigou** [comment] 2021-04-27 07:19
I'm not able to reproduce the issue on my own machine (macOS) using a fresh install of both RetroPath RL and rp3_dcache. How did you install the rp3_dcache?

**Comment by Dovehya** [comment] 2021-04-27 07:29
> I'm not able to reproduce the issue on my own machine (macOS) using a fresh install of both RetroPath RL and rp3_dcache. How did you install the rp3_dcache?

I just did as README.md in the rp3_dcache repository. Before I set up python environment, I have installed docker engine and docker-compose,.And they can run normally. After that, I git the repository "rp3_dcache" to my local disks. And then used the command  `pip install -e .` to install the rp3_dache. Finally, I run the docker-compose with the command `docker-compose -f service/run/mongo.yml up -d.`
All of these have been done, I used the command
`python change_config.py --use_cache True --add_Hs True
pytest -v`
And it gave out errors.

Did I omit some steps?
Thanks~

**Comment by tduigou** [comment] 2021-04-27 20:30
Hi @Dovehya, the installation steps sounds good. I pushed some changes on a `fix-mongo-connect` branch of rp3_dcache. Could you checkout this branch and check if the issue is still here?

**Comment by Dovehya** [comment] 2021-04-28 03:32
> Hi @Dovehya, the installation steps sounds good. I pushed some changes on a `fix-mongo-connect` branch of rp3_dcache. Could you checkout this branch and check if the issue is still here?

Hi,@tduigou , the problem has been resolved. Really thanks for your heartful reply.

**Comment by tduigou** [comment] 2021-04-28 06:20
Great! I'll close the issue.

For the record the ` pymongo.errors.ConfigurationError: Unknown option username` raised by the `MongoClient` init  seems to be solved by providing the `username` and `password` through the `uri` parameter.

**Closed by tduigou** 2021-04-28 06:20 UTC
